### ISSUE TITLE
Email "To" property not parsed

### ISSUE THREAD

**Issue by vnirvik** [ValentinKostyuk/SmtpServerStub#3]
Hi,
I send email to your stub. Received mail contains property "MailMessageDataSection" like:
MIME-Version: 1.0
Sender: "Smtp Name" <smtp@sender.ru>
From: "Smtp Name" <smtp@sender.ru>
To: feedback@support.ru
Date: 7 Aug 2020 12:54:39 +0300
Subject: Feedback subject
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: base64
X-Antivirus: Avast (VPS 200806-10, 06.08.2020), Outbound message
X-Antivirus-Status: Clean

But received mail property "To" doesn't contain any. So I need to write anything like:
            if (actual.To.Any())
            {
                Assert.AreEqual(FeedbackSupportEmail, actual.To[0].Address);
            }
            else
            {
                Assert.IsTrue(actual.MailMessageDataSection.Contains($"To: {FeedbackSupportEmail}"));
            }

Thank you for attention,
Vladimir.

**Comment by ValentynKostiuk** [comment]
Hi Vladimir,
Thanks for feedback!

I will take a look on your problem during this weekend.

Is my understanding correct that e-mail you send contains "To" header but Stub constantly returns empty collection in "actual.To"?

Thanks,
Valentin

**Comment by vnirvik** [comment]
Hi Valentin,
Yes of course, collection “actual.To” is empty.
Vladimir Nikolaev.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ValentynKostiuk** [comment]
Hi @vnirvik,

Looks like I've fixed issue.

Could you please verify fix works for you on this package build 

PM> Install-Package SmtpServerStub -Version 1.1.161-I-3

If you are using UI of Nuget Package Manager please check "Include prerelease" flag is ticked.

Thanks,
Valentyn

**Comment by vnirvik** [comment]
Hi,
I checked version 1.1.161-I-3. Problem has been resolved.
Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ValentynKostiuk** [comment]
Hi @vnirvik,

Thanks for checking and reporting this bug!

During this week I will merge this fix to new release version and inform you when it's done.

Appreciate you help,
Valentyn

**Comment by ValentynKostiuk** [comment]
Hi @vnirvik,

I've merged this fix to master 
so you can use **_Install-Package SmtpServerStub -Version 1.1.183_** command to update to latest stable version
Also symbols are now published to nuget.org
Thanks for reporting issue!
